[package]
name = "twentytwo"
version = "1.0.0"
authors = ["Gasper <gasper(a)gmx.com>"]

[[bin]]
name = "twentytwo"
path = "twentytwo.rs"
test = true

[dependencies]
itertools = "0.8.2"
num-bigint = "0.2.4"
num-traits = "0.2.10"